### ISSUE TITLE
Broken PATCH when I want to change the category of a product

### ISSUE THREAD

**Issue by cedricgautier** [KrispyTech/airneis#100]
- When I want to change the category on a specific product, I am unable to make the PATCH. 
<img width="1007" alt="Screenshot 2024-04-18 at 11 49 16" src="https://github.com/KrispyTech/airneis/assets/75094434/d673537f-aefe-4a34-885d-fb9422164c71">

**Comment by BarnabePILLIAUDIN** [comment]
Bug handled in this PR
https://github.com/KrispyTech/airneis/pull/99

**Comment by BarnabePILLIAUDIN** [comment]
Bug handled in this PR
https://github.com/KrispyTech/airneis/pull/99
